name: Auto Generate and Replace Reference Files

on: [push]

jobs:
  generate_reference-and-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: download appledoc
      run: |
        wget https://github.com/tomaz/appledoc/archive/refs/heads/master.zip
    - name: unzip appledoc
      uses: montudor/action-zip@v1
      with:
        args: unzip -qq master.zip -d appledoc-master
    - run: sudo chown -R runner appledoc-master
    - run: |
        cd appledoc-master
        sudo sh install-appledoc.sh
        appledoc --version
        appledoc AppledocSetting.plist
        ls

    # - name: Setup git
    #   env:
    #     EMAIL: ${{ secrets.EMAIL }}
    #   run: |
    #     git config --global user.email "$EMAIL"
    #     git config --global user.name "tanaka-kokoro"
    # - name: Commit docs
    #   run: |
    #     git add -N .
    #     if ! git diff --exit-code --quiet
    #     then
    #       git add .
    #       git commit -m "Auto replace reference files"
    #       git push
    #     fi
    # - name: zip docs
    #   run: zip -r docs.zip docs/

    # - name: Archive artifacts
    #   uses: actions/upload-artifact@v2
    #   with:
    #     name: docs
    #     path: docs.zip